on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: ./gradlew :quarkus:build
        env:
          QUARKUS_CONTAINER_IMAGE_BUILD: true
          QUARKUS_CONTAINER_IMAGE_PUSH: true
          QUARKUS_CONTAINER_IMAGE_IMAGE: fluxroot/techstacks-quarkus:1.0.0
          QUARKUS_CONTAINER_IMAGE_USERNAME: ${{ secrets.DOCKER_HUB_PASSWORD }}
          QUARKUS_CONTAINER_IMAGE_PASSWORD: ${{ secrets.DOCKER_HUB_USERNAME }}
